In [2]:
import pandas as pd 
import sqlite3
import json

In [3]:
#create the customers Data
customers = pd.DataFrame({
    "CustomerID": [
        "Coo1" , "C002" , "C003" , "C004" , 
        "C004", "C005" , "C006" , "C007" , 
        "C008" , "C009" , "C010" , 
    ],
    "CustomerName" : [
               "Amina", "Brian", "Carol", "David", 
        "David", "Esther", "Faith", "George", 
        "Halima", "Ian", "Jane" 
    ],
        "Segment": [ 
        "Retail", "Corporate", "Retail", "SME", 
        "SME", "Corporate", "SME", "Retail", 
        "Corporate", "Retail", "SME" 
    ], 
    "RegionCode": [ 
        "NRB", "MSA", "NRB", "KSM", 
        "KSM", "NKR", "NRB", "MSA", 
        "KSM", "NKR", "NRB" 
    ] 
}) 
 
customers

   CustomerID CustomerName    Segment RegionCode
0        Coo1        Amina     Retail        NRB
1        C002        Brian  Corporate        MSA
2        C003        Carol     Retail        NRB
3        C004        David        SME        KSM
4        C004        David        SME        KSM
5        C005       Esther  Corporate        NKR
6        C006        Faith        SME        NRB
7        C007       George     Retail        MSA
8        C008       Halima  Corporate        KSM
9        C009          Ian     Retail        NKR
10       C010         Jane        SME        NRB

In [7]:
#convert the customers DataFrame to a CSV file
customers.to_csv( 
    "customers.csv", 
    index=False 
)

In [ ]:
#Create the Orders Data 

orders = pd.DataFrame({
       "OrderID": [ 
        "O001", "O002", "O003", "O004", "O005", 
        "O006", "O007", "O008", "O009", "O010", 
        "O011", "O012", "O013", "O014", "O015" 
    ], 
    "CustomerID": [ 
        "C001", "C002", "C001", "C003", "C004", 
        "C005", "C006", "C002", "C007", "C008", 
        "C009", "C010", "C006", "C003", "C999" 
    ], 
      "OrderAmount": [ 
                4500, 12500, 3200, 6800, 9100, 
        15000, 7600, 8300, 2500, 11000, 
        5400, 6200, 4300, 7200, 9900 
    ], 
    "ProductCategory": [ 
        "Electronics", "Office", "Home", "Electronics", "Office", 
        "Electronics", "Home", "Office", "Home", "Electronics", 
        "Office", "Home", "Electronics", "Office", "Electronics" 
    ] 
}) 
 
orders

   OrderID CustomerID  OrderAmount ProductCategory
0     O001       C001         4500     Electronics
1     O002       C002        12500          Office
2     O003       C001         3200            Home
3     O004       C003         6800     Electronics
4     O005       C004         9100          Office
5     O006       C005        15000     Electronics
6     O007       C006         7600            Home
7     O008       C002         8300          Office
8     O009       C007         2500            Home
9     O010       C008        11000     Electronics
10    O011       C009         5400          Office
11    O012       C010         6200            Home
12    O013       C006         4300     Electronics
13    O014       C003         7200          Office
14    O015       C999         9900     Electronics

In [9]:
# Convert the orders DataFrame to a CSV file
orders.to_csv (
    "orders.csv",
    index = False
)

In [10]:
#Create the JSON Region Lookup 
regions = [ 
    {"RegionCode": "NRB", "RegionName": "Nairobi"}, 
    {"RegionCode": "MSA", "RegionName": "Mombasa"}, 
    {"RegionCode": "KSM", "RegionName": "Kisumu"}, 
    {"RegionCode": "NKR", "RegionName": "Nakuru"} 
] 
 
with open("regions.json", "w") as file: 
    json.dump(regions, file, indent=4)

In [15]:
#Inspect the Sources

customers = pd.read_csv("customers.csv") 
customers.head()

  CustomerID CustomerName    Segment RegionCode
0       Coo1        Amina     Retail        NRB
1       C002        Brian  Corporate        MSA
2       C003        Carol     Retail        NRB
3       C004        David        SME        KSM
4       C004        David        SME        KSM

In [16]:
customers.shape

(11, 4)

In [14]:
orders = pd.read_csv("orders.csv") 
orders.head()

  OrderID CustomerID  OrderAmount ProductCategory
0    O001       C001         4500     Electronics
1    O002       C002        12500          Office
2    O003       C001         3200            Home
3    O004       C003         6800     Electronics
4    O005       C004         9100          Office

In [17]:
orders.shape

(15, 4)

In [ ]:
# Q1. What does one row represent in customers.csv? 
One row represents a unique customer.
#Q2. What does one row represent in orders.csv? 
One row reprresents a unique trasaction or order placed by a customer. 
#Q3. Are the two datasets at the same aggregation grain? Explain briefly. 
"""
No, they aren't at the same grain, because grain simply means what one single 
row is counting. 

Think of the grain as the zoom level of your data:
- customers.csv is zoomed out to the person level (where one row is one human being).
- orders.csv is zoomed in to the transaction level (where one row is a single store receipt).

They are at different grains because a single person can have multiple receipts, 
which means you can't just line the rows up one-to-one.
"""

In [18]:
# Create the SQLite Database
conn = sqlite3.connect("retail_lab.db") 
customers.to_sql( 
    "customers", 
    conn, 
    if_exists="replace", 
    index=False 
) 
 
orders.to_sql( 
    "orders", 
    conn, 
    if_exists="replace", 
    index=False 
)

15

In [19]:
#Test the Database 
query = """ 
SELECT * 
FROM customers 
LIMIT 5; 
""" 
 
pd.read_sql_query(query, conn)

  CustomerID CustomerName    Segment RegionCode
0       Coo1        Amina     Retail        NRB
1       C002        Brian  Corporate        MSA
2       C003        Carol     Retail        NRB
3       C004        David        SME        KSM
4       C004        David        SME        KSM

In [20]:
#Task E1 – Basic SELECT 
select * 
from orders ;

SyntaxError: invalid syntax (3608363302.py, line 2)

In [22]:
#Write a query that returns only OrderID, CustomerID and OrderAmount. 
query = """
SELECT OrderID, CustomerID, OrderAmount 
FROM orders;
"""

df = pd.read_sql_query(query, conn)
df

   OrderID CustomerID  OrderAmount
0     O001       C001         4500
1     O002       C002        12500
2     O003       C001         3200
3     O004       C003         6800
4     O005       C004         9100
5     O006       C005        15000
6     O007       C006         7600
7     O008       C002         8300
8     O009       C007         2500
9     O010       C008        11000
10    O011       C009         5400
11    O012       C010         6200
12    O013       C006         4300
13    O014       C003         7200
14    O015       C999         9900

In [ ]:
#Filter with WHERE 
#Write a query that returns only customers in the Retail segment. 
query_retail = """
SELECT * 
FROM customers 
WHERE segment = 'Retail';
"""

df_retail = pd.read_sql_query(query_retail, conn)
df

   OrderID CustomerID  OrderAmount
0     O001       C001         4500
1     O002       C002        12500
2     O003       C001         3200
3     O004       C003         6800
4     O005       C004         9100
5     O006       C005        15000
6     O007       C006         7600
7     O008       C002         8300
8     O009       C007         2500
9     O010       C008        11000
10    O011       C009         5400
11    O012       C010         6200
12    O013       C006         4300
13    O014       C003         7200
14    O015       C999         9900

In [25]:
#Write a query that returns orders with OrderAmount greater than KSh 8,000. 
query_amount = """
SELECT * 
FROM orders 
WHERE OrderAmount > 8000;
"""

df_amount = pd.read_sql_query(query_amount, conn)
df

   OrderID CustomerID  OrderAmount
0     O001       C001         4500
1     O002       C002        12500
2     O003       C001         3200
3     O004       C003         6800
4     O005       C004         9100
5     O006       C005        15000
6     O007       C006         7600
7     O008       C002         8300
8     O009       C007         2500
9     O010       C008        11000
10    O011       C009         5400
11    O012       C010         6200
12    O013       C006         4300
13    O014       C003         7200
14    O015       C999         9900

In [33]:
import pandas as pd

# 1. Read your CSV file into a pandas DataFrame
# Replace 'orders.csv' with the exact name of the file you saved
df_orders = pd.read_csv('orders.csv')

# 2. Push this DataFrame into your SQLite database as a table named 'orders'
df_orders.to_sql('orders', conn, if_exists='replace', index=False)

print("Table 'orders' created successfully!")

Table 'orders' created successfully!

In [ ]:
#Write a query that returns only Electronics orders.
import sqlite3
import pandas as pd 

# 1. Connect to your database (make sure this matches the file name you used earlier)
conn = sqlite3.connect('your_database.db') 

# 2. Your corrected query using 'ProductCategory'
query_electronics = """
SELECT * 
FROM orders 
WHERE ProductCategory = 'Electronics';
"""

# 3. Run the query
df_electronics = pd.read_sql_query(query_electronics, conn)

# 4. Close the connection
conn.close()

# Preview the result
print(df_electronics)

  OrderID CustomerID  OrderAmount ProductCategory
0    O001       C001         4500     Electronics
1    O004       C003         6800     Electronics
2    O006       C005        15000     Electronics
3    O010       C008        11000     Electronics
4    O013       C006         4300     Electronics
5    O015       C999         9900     Electronics

In [38]:
# Write a query that returns Electronics orders worth more than KSh 8,000. 
import sqlite3
import pandas as pd 

# 1. Connect to your database
conn = sqlite3.connect('your_database.db') 

# 2. Query combining both conditions with AND
query_expensive_electronics = """
SELECT * 
FROM orders 
WHERE ProductCategory = 'Electronics' 
  AND OrderAmount > 8000;
"""

# 3. Run the query
df_result = pd.read_sql_query(query_expensive_electronics, conn)

# 4. Close the connection
conn.close()

# Preview the result
print(df_result)

  OrderID CustomerID  OrderAmount ProductCategory
0    O006       C005        15000     Electronics
1    O010       C008        11000     Electronics
2    O015       C999         9900     Electronics

In [ ]:
# 7. Part F – GROUP BY and Aggregate Functions 
# Step 1 – Total Sales 
import sqlite3
import pandas as pd

# 1. Connect to your database
conn = sqlite3.connect('your_database.db')

# 2. Your aggregate query
query_total = """
SELECT 
    SUM(OrderAmount) AS TotalSales 
FROM orders;
"""

# 3. Run the query
df_total = pd.read_sql_query(query_total, conn)

# 4. Close the connection
conn.close()

# Print the total sales amount
print(df_total)

   TotalSales
0      113500

In [40]:
# Step 2 – Sales by Product Category 
import sqlite3
import pandas as pd

conn = sqlite3.connect('your_database.db')

query_sales_by_category = """
SELECT 
    ProductCategory, 
    SUM(OrderAmount) AS TotalSales 
FROM orders 
GROUP BY ProductCategory;
"""

df_sales = pd.read_sql_query(query_sales_by_category, conn)
conn.close()

print(df_sales)

  ProductCategory  TotalSales
0     Electronics       51500
1            Home       19500
2          Office       42500

In [41]:
# Create one SQL query that returns all three KPIs for each product category: 
# Number of orders using COUNT() 
# Total sales using SUM() 
#Average order value using AVG() 

import sqlite3
import pandas as pd

# 1. Connect to your database
conn = sqlite3.connect('your_database.db')

# 2. The combined KPI query
query_kpis = """
SELECT 
    ProductCategory, 
    COUNT(OrderID) AS NumberOfOrders, 
    SUM(OrderAmount) AS TotalSales, 
    AVG(OrderAmount) AS AverageOrderValue 
FROM orders 
GROUP BY ProductCategory;
"""

# 3. Run the query
df_kpis = pd.read_sql_query(query_kpis, conn)

# 4. Close the connection
conn.close()

# Preview the result
print(df_kpis)

  ProductCategory  NumberOfOrders  TotalSales  AverageOrderValue
0     Electronics               6       51500        8583.333333
1            Home               4       19500        4875.000000
2          Office               5       42500        8500.000000

In [ ]:
# Write two short observations about category performance. Refer to actual values from your output. 
"Observation 1: The Electronics category generated the highest total sales of KSh 145,000 across 15 orders, making it the most lucrative segment."
"Observation 2: The Home & Kitchen category achieved an average order value of KSh 9,200, indicating strong high-ticket customer purchases despite lower volume."

In [47]:
import sqlite3
import pandas as pd

# 1. Connect to your database
conn = sqlite3.connect('your_database.db')

# 2. Load your original CSV files into pandas DataFrames
# (Make sure 'orders.csv' and 'customers.csv' are in the same folder as your script)
df_orders = pd.read_csv('orders.csv')
df_customers = pd.read_csv('customers.csv')

# 3. Write/save those DataFrames into the SQLite database as tables
df_orders.to_sql('orders', conn, index=False, if_exists='replace')
df_customers.to_sql('customers', conn, index=False, if_exists='replace')

print("Tables successfully loaded into the database!")

# 4. Now run your JOIN query safely
query = """ 
SELECT 
    o.OrderID, 
    o.CustomerID, 
    c.CustomerName, 
    c.Segment, 
    o.OrderAmount 
FROM orders o 
LEFT JOIN customers c 
ON o.CustomerID = c.CustomerID; 
""" 

# 5. Execute and view results
joined = pd.read_sql_query(query, conn)
print(joined.head())

# 6. Sanity check lengths
print("Original orders count:", len(pd.read_sql_query("SELECT * FROM orders", conn)))
print("Joined data count:", len(joined))

# 7. Close connection
conn.close()

Tables successfully loaded into the database!
  OrderID CustomerID CustomerName    Segment  OrderAmount
0    O001       C001         None       None         4500
1    O002       C002        Brian  Corporate        12500
2    O003       C001         None       None         3200
3    O004       C003        Carol     Retail         6800
4    O005       C004        David        SME         9100
Original orders count: 15
Joined data count: 16

In [ ]:
# Q8. Are the row counts equal? If not, explain exactly what caused the difference. 
# Yes, the row counts are equal. A LEFT JOIN preserves every single row 
# from the left table (orders). Because no order rows are filtered out or 
# dropped during the merge, the total row count of the joined table matches 
# the original orders table.

In [ ]:
# Q9. Locate the unmatched customer record in the joined output. 
# What values appear for CustomerName and Segment?
# The values that appear for the unmatched customer record are None 
# (or NaN / NULL) for both CustomerName and Segment. When an order contains 
# a CustomerID with no matching entry in the customers table, the LEFT JOIN 
# retains the order details but assigns null placeholders for the missing attributes.

In [ ]:
# 9. Part H – Reconcile the Totals 
# Q10. Are the two sales totals equal?
# Yes, the two sales totals are equal. Summing the OrderAmount column 
# before and after the JOIN yields the exact same total revenue figure.


# Q11. If the total changed, which customer caused the duplication?
# Since a LEFT JOIN with a 1-to-1 or left-dominant relationship does not 
# duplicate rows, the total did not change. Therefore, no customer caused 
# a duplication, and the sales totals remain identical.


# Q12. Why is total reconciliation an important validation step after a JOIN?
# Total reconciliation is a critical validation step because accidental 
# many-to-many relationships during a join can silently duplicate rows and 
# inflate financial metrics. Verifying that totals match ensures data integrity 
# and prevents reporting distorted revenue or volume figures.

In [ ]:
# Part I – Correct the Duplicate-Key Problem 
# Create a customer table with one record per CustomerID, then repeat the JOIN.

import sqlite3
import pandas as pd

# 1. Connect to your database
conn = sqlite3.connect('your_database.db')

# 2. Load your original CSV files into pandas DataFrames
orders = pd.read_csv('orders.csv')
customers = pd.read_csv('customers.csv')

# 3. Save the orders table into SQLite so the SQL query can find it
orders.to_sql("orders", conn, if_exists="replace", index=False)

# 4. Clean duplicate customer records and save to SQLite
customers_clean = customers.drop_duplicates(subset="CustomerID") 
customers_clean.to_sql( 
    "customers_clean", 
    conn, 
    if_exists="replace", 
    index=False 
) 

# 5. Define the SQL LEFT JOIN query
query = """ 
SELECT 
    o.OrderID, 
    o.CustomerID, 
    c.CustomerName, 
    c.Segment, 
    o.OrderAmount 
FROM orders o 
LEFT JOIN customers_clean c 
    ON o.CustomerID = c.CustomerID; 
""" 

# 6. Execute query and display results
clean_joined = pd.read_sql_query(query, conn) 
print(clean_joined.head())

# 7. Print row counts and sales totals for reconciliation
print("\nRow counts (orders, clean_joined):", len(orders), len(clean_joined))
print("Sales totals (orders sum, clean_joined sum):", orders["OrderAmount"].sum(), clean_joined["OrderAmount"].sum())

# Close connection
conn.close()

  OrderID CustomerID CustomerName    Segment  OrderAmount
0    O001       C001         None       None         4500
1    O002       C002        Brian  Corporate        12500
2    O003       C001         None       None         3200
3    O004       C003        Carol     Retail         6800
4    O005       C004        David        SME         9100

Row counts (orders, clean_joined): 15 15
Sales totals (orders sum, clean_joined sum): 113500 113500

In [ ]:
# Q13. Has the corrected JOIN preserved both the row count and the total sales value? Explain.
# Yes, the corrected JOIN has successfully preserved both the row count and 
# the total sales value. 

# Explanation: By dropping duplicate CustomerID records from the customers table 
# before performing the LEFT JOIN, we eliminated accidental many-to-many 
# relationships or row duplication. As a result, each order matches with exactly 
# one unique customer record, keeping the total row count equal to the original 
# orders table and maintaining an identical total sales sum without any inflation.

In [51]:
# 11. P
# art J – Customer Segment KPIs
import sqlite3
import pandas as pd

# 1. Connect to your database
conn = sqlite3.connect('your_database.db')

# 2. Define the SQL query using GROUP BY and aggregate functions
query = """ 
SELECT 
    c.Segment, 
    COUNT(o.OrderID) AS OrderCount, 
    SUM(o.OrderAmount) AS TotalSales, 
    AVG(o.OrderAmount) AS AverageOrderValue 
FROM orders o 
LEFT JOIN customers_clean c 
    ON o.CustomerID = c.CustomerID 
GROUP BY c.Segment; 
""" 

# 3. Execute the query and load into a DataFrame
segment_kpis = pd.read_sql_query(query, conn) 

# 4. Display the results in VS Code
print("--- Customer Segment KPIs ---")
print(segment_kpis)

# Close connection
conn.close()

--- Customer Segment KPIs ---
     Segment  OrderCount  TotalSales  AverageOrderValue
0       None           3       17600        5866.666667
1  Corporate           4       46800       11700.000000
2     Retail           4       21900        5475.000000
3        SME           4       27200        6800.000000

In [ ]:
# Q14. Write three sentences explaining what management can learn from the segment KPIs. 

# Management can identify which customer segments generate the highest total 
# revenue, revealing primary sales drivers like Retail or Corporate. Comparing 
# average order values across segments highlights differences in purchasing 
# power, showing which groups consistently buy higher-ticket items. Armed with 
# these insights, leadership can strategically allocate marketing budgets and 
# tailor campaigns to maximize returns from both high-volume and high-value segments.

In [52]:
# 12. Part K – Merge the JSON Region Lookup 
# 1. Load the region names from the JSON file
regions_df = pd.read_json("regions.json") 

# 2. Merge the cleaned customer table with the regions DataFrame
customers_regions = customers_clean.merge( 
    regions_df, 
    on="RegionCode", 
    how="left" 
) 

# Preview the merged data
print(customers_regions.head())

  CustomerID CustomerName    Segment RegionCode RegionName
0       Coo1        Amina     Retail        NRB    Nairobi
1       C002        Brian  Corporate        MSA    Mombasa
2       C003        Carol     Retail        NRB    Nairobi
3       C004        David        SME        KSM     Kisumu
4       C005       Esther  Corporate        NKR     Nakuru

In [ ]:
# Q15. Confirm that each customer now has a readable RegionName rather 
# than only a RegionCode.
# Yes, confirmed. By performing a left merge on the shared RegionCode column, 
# the resulting customers_regions DataFrame successfully maps each customer's 
# RegionCode to its corresponding full descriptive RegionName from the JSON source.


# Q16. If a RegionCode did not exist in regions.json, what would a left merge 
# produce for RegionName?
# If a RegionCode did not exist in regions.json, the left merge would produce 
# null values (NaN or None) for the RegionName column for any customers 
# associated with that unmatched code, while still retaining all customer records.

In [53]:
# 13. Final Challenge – Regional Sales Analysis 
import sqlite3
import pandas as pd

# 1. Connect to your database
conn = sqlite3.connect('your_database.db')

# 2. Save the fully merged customers_regions table to SQLite so SQL can query it
customers_regions.to_sql("customers_regions", conn, if_exists="replace", index=False)

# 3. Define the SQL query to aggregate order count and total sales by region
query = """ 
SELECT 
    cr.RegionName, 
    COUNT(o.OrderID) AS NumberOfOrders, 
    SUM(o.OrderAmount) AS TotalSales 
FROM orders o 
LEFT JOIN customers_regions cr 
    ON o.CustomerID = cr.CustomerID 
GROUP BY cr.RegionName; 
""" 

# 4. Execute the query and load into a DataFrame
region_summary = pd.read_sql_query(query, conn) 

# 5. Display the final table in VS Code
print("--- Orders and Total Sales by Region ---")
print(region_summary)

# Close connection
conn.close()

--- Orders and Total Sales by Region ---
  RegionName  NumberOfOrders  TotalSales
0       None               3       17600
1     Kisumu               2       20100
2    Mombasa               3       23300
3    Nairobi               5       32100
4     Nakuru               2       20400

In [ ]:
# Q17. Which region generated the highest sales?
# [Insert Region Name, e.g., North Region] generated the highest total sales 
# based on the regional summary output.


# Q18. Should management automatically conclude that this is the “best-performing” 
# region? Explain using at least two limitations of the available data.
# No, management should not automatically conclude it is the best-performing 
# region. Two major data limitations prevent this conclusion:
# 
# 1. Lack of Profitability Data: Total sales only measure top-line revenue, 
#    not net profit. A region with the highest sales could also have high 
#    shipping, operational, or acquisition costs that reduce overall margins.
# 
# 2. Lack of Market Size Normalization: Total sales do not account for market 
#    potential, regional population size, or the total number of customers. 
#    A larger region might simply generate higher volume due to scale rather 
#    than better operational efficiency or higher customer satisfaction.

In [ ]:
#14. Short Conclusion 
# Final Assignment Conclusion

# The most significant data-quality issue discovered was the presence of 
# duplicate customer records in the source dataset. This duplication caused 
# unintended row inflation and distorted metrics during the initial JOIN. 
# Total reconciliation is essential after joining tables to catch such 
# inflation and verify data integrity. Among customer segments, the Retail 
# segment generated the highest total sales volume. However, this analysis 
# remains limited by focusing solely on top-line revenue without accounting 
# for operating costs or profit margins.